name = "NVTX"
uuid = "5da4648a-3479-48b8-97b9-01cb529c0a1f"
authors = ["Simon Byrne <simonbyrne@gmail.com>"]
version = "0.1.2"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"

[compat]
julia = "1.6"
Colors = "0.12"
