name: CI

on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:

jobs:
  Linux:
    strategy:
      matrix:
        julia_version:
          - "1.6"
          - "1"
          - "nightly"

    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
    - name: Install Nsight Systems
      run: sudo apt install nsight-systems
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia_version }}
    - uses: julia-actions/cache@v1
    - uses: julia-actions/julia-buildpkg@v1
    - uses: julia-actions/julia-runtest@v1
    - uses: actions/upload-artifact@v3
      with:
        name: nsys ${{ matrix.julia_version }}
        path: output/
